config/routes.rb
GoodAndEvilKings::Application.routes.draw do

  get 'preview' => 'preview#index', as: 'preview'

  resources :message_categories

  resources :messages

  resources :diplomacies, only: [:index, :show]

  
  namespace :admin do
    resources :ai_actions
    resources :castles
    resources :building_types
    resources :mission_types
    resources :mission_lengths
    resources :mission_statuses
    resources :name_fragments
    resources :ressources
    resources :soldier_types
  end
  resources :buildings, except: [:index]
  get 'buildings/:id/upgrade' => 'buildings#upgrade', as: 'upgrade_building'
  post 'buildings/:id/upgrade' => 'buildings#upgrade_now'

  resources :missions do
    resources :missions, only: [:new, :create]
  end
  get 'missions/:id/redeem' => 'missions#redeem'

  resources :garrisons, only: [:show, :destroy, :new, :create]
  get ':type/:id/garrisons' => 'garrisons#index', as: 'garrisons_for'

  resources :stocks, except: [:index]

  resources :kingdoms
  
  get 'tiles/list' => 'tiles#list'
  post 'tiles/partial' => 'tiles#partial'
  resources :tiles
  resources :castles do
    resources :missions, only: [:new, :create]
    resources :garrisons, only: [:new, :create]
    resources :buildings, only: [:new, :create]
  end

  devise_for :users

  root 'tiles#index'

  

end

app/controllers/admin/mission_types_controller.rb
module Admin
  class MissionTypesController < AdminController
    before_action :set_mission_type, only: [:show, :edit, :update, :destroy]

    # GET /mission_types
    # GET /mission_types.json
    def index
      @mission_types = MissionType.all
    end

    # GET /mission_types/1
    # GET /mission_types/1.json
    def show
    end

    # GET /mission_types/new
    def new
      @mission_type = MissionType.new
    end

    # GET /mission_types/1/edit
    def edit
    end

    # POST /mission_types
    # POST /mission_types.json
    def create
      @mission_type = MissionType.new(mission_type_params)

      respond_to do |format|
        if @mission_type.save
          format.html { redirect_to [:admin, @mission_type], notice: 'Mission type was successfully created.' }
          format.json { render action: 'show', status: :created, location: @mission_type }
        else
          format.html { render action: 'new' }
          format.json { render json: @mission_type.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /mission_types/1
    # PATCH/PUT /mission_types/1.json
    def update
      respond_to do |format|
        if @mission_type.update(mission_type_params)
          format.html { redirect_to [:admin, @mission_type], notice: 'Mission type was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @mission_type.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /mission_types/1
    # DELETE /mission_types/1.json
    def destroy
      @mission_type.destroy
      respond_to do |format|
        format.html { redirect_to admin_mission_types_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_mission_type
        @mission_type = MissionType.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def mission_type_params
        params.require(:mission_type).permit(
          :name, :class_name,
          options_attributes: [:name, :val, :id, :_destroy],
          mission_lengths_attributes: [:label, :seconds, :reward, :id, :_destroy]
        )
      end
  end
end

app/helpers/mission_types_helper.rb
module MissionTypesHelper
end

app/views/admin/mission_types/_form.html.erb
<%= nested_form_for([:admin,@mission_type]) do |f| %>
  <% if @mission_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mission_type.errors.count, "error") %> prohibited this mission_type from being saved:</h2>

      <ul>
      <% @mission_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :class_name %><br>
    <%= f.text_field :class_name %>
  </div>
  
  <%= render 'options/nested_form', :form => f %>
  <%= render 'admin/mission_lengths/nested_form', :form => f %>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/mission_types/edit.html.erb
<h1>Editing mission_type</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @mission_type] %> |
<%= link_to 'Back', admin_mission_types_path %>

app/views/admin/mission_types/index.html.erb
<h1>Listing mission_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Class name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mission_types.each do |mission_type| %>
      <tr>
        <td><%= mission_type.name %></td>
        <td><%= mission_type.class_name %></td>
        <td><%= link_to 'Show', [:admin, mission_type] %></td>
        <td><%= link_to 'Edit', edit_admin_mission_type_path(mission_type) %></td>
        <td><%= link_to 'Destroy', [:admin, mission_type], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mission type', new_admin_mission_type_path %>

app/views/admin/mission_types/new.html.erb
<h1>New mission_type</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_mission_types_path %>

app/views/admin/mission_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mission_type.name %>
</p>

<p>
  <strong>Class name:</strong>
  <%= @mission_type.class_name %>
</p>

<%= link_to 'Edit', edit_admin_mission_type_path(@mission_type) %> |
<%= link_to 'Back', admin_mission_types_path %>