config/routes.rb
GoodAndEvilKings::Application.routes.draw do

  get 'preview' => 'preview#index', as: 'preview'

  resources :message_categories

  resources :messages

  resources :diplomacies, only: [:index, :show]

  
  namespace :admin do
    resources :ai_actions
    resources :castles
    resources :building_types
    resources :mission_types
    resources :mission_lengths
    resources :mission_statuses
    resources :name_fragments
    resources :ressources
    resources :soldier_types
  end
  resources :buildings, except: [:index]
  get 'buildings/:id/upgrade' => 'buildings#upgrade', as: 'upgrade_building'
  post 'buildings/:id/upgrade' => 'buildings#upgrade_now'

  resources :missions do
    resources :missions, only: [:new, :create]
  end
  get 'missions/:id/redeem' => 'missions#redeem'

  resources :garrisons, only: [:show, :destroy, :new, :create]
  get ':type/:id/garrisons' => 'garrisons#index', as: 'garrisons_for'

  resources :stocks, except: [:index]

  resources :kingdoms
  
  get 'tiles/list' => 'tiles#list'
  post 'tiles/partial' => 'tiles#partial'
  resources :tiles
  resources :castles do
    resources :missions, only: [:new, :create]
    resources :garrisons, only: [:new, :create]
    resources :buildings, only: [:new, :create]
  end

  devise_for :users

  root 'tiles#index'

  

end

app/controllers/admin/mission_statuses_controller.rb
module Admin
  class MissionStatusesController < AdminController
    before_action :set_mission_status, only: [:show, :edit, :update, :destroy]

    # GET /mission_statuses
    # GET /mission_statuses.json
    def index
      @mission_statuses = MissionStatus.all
    end

    # GET /mission_statuses/1
    # GET /mission_statuses/1.json
    def show
    end

    # GET /mission_statuses/new
    def new
      @mission_status = MissionStatus.new
    end

    # GET /mission_statuses/1/edit
    def edit
    end

    # POST /mission_statuses
    # POST /mission_statuses.json
    def create
      @mission_status = MissionStatus.new(mission_status_params)

      respond_to do |format|
        if @mission_status.save
          format.html { redirect_to [:admin, @mission_status], notice: 'Mission status was successfully created.' }
          format.json { render action: 'show', status: :created, location: @mission_status }
        else
          format.html { render action: 'new' }
          format.json { render json: @mission_status.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /mission_statuses/1
    # PATCH/PUT /mission_statuses/1.json
    def update
      respond_to do |format|
        if @mission_status.update(mission_status_params)
          format.html { redirect_to [:admin, @mission_status], notice: 'Mission status was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @mission_status.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /mission_statuses/1
    # DELETE /mission_statuses/1.json
    def destroy
      @mission_status.destroy
      respond_to do |format|
        format.html { redirect_to admin_mission_statuses_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_mission_status
        @mission_status = MissionStatus.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def mission_status_params
        params.require(:mission_status).permit(:name, :code)
      end
  end
end

app/helpers/mission_statuses_helper.rb
module MissionStatusesHelper
end

app/views/admin/mission_statuses/_form.html.erb
<%= form_for([:admin,@mission_status]) do |f| %>
  <% if @mission_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mission_status.errors.count, "error") %> prohibited this mission_status from being saved:</h2>

      <ul>
      <% @mission_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/mission_statuses/edit.html.erb
<h1>Editing mission_status</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @mission_status] %> |
<%= link_to 'Back', admin_mission_statuses_path %>

app/views/admin/mission_statuses/index.html.erb
<h1>Listing mission_statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @mission_statuses.each do |mission_status| %>
      <tr>
        <td><%= mission_status.name %></td>
        <td><%= mission_status.code %></td>
        <td><%= link_to 'Show', [:admin, mission_status] %></td>
        <td><%= link_to 'Edit', edit_admin_mission_status_path(mission_status) %></td>
        <td><%= link_to 'Destroy', [:admin, mission_status], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mission status', new_admin_mission_status_path %>

app/views/admin/mission_statuses/new.html.erb
<h1>New mission_status</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_mission_statuses_path %>

app/views/admin/mission_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @mission_status.name %>
</p>

<p>
  <strong>Code:</strong>
  <%= @mission_status.code %>
</p>

<%= link_to 'Edit', edit_admin_mission_status_path(@mission_status) %> |
<%= link_to 'Back', admin_mission_statuses_path %>