config/routes.rb
GoodAndEvilKings::Application.routes.draw do

  get 'preview' => 'preview#index', as: 'preview'

  resources :message_categories

  resources :messages

  resources :diplomacies, only: [:index, :show]

  
  namespace :admin do
    resources :ai_actions
    resources :castles
    resources :building_types
    resources :mission_types
    resources :mission_lengths
    resources :mission_statuses
    resources :name_fragments
    resources :ressources
    resources :soldier_types
  end
  resources :buildings, except: [:index]
  get 'buildings/:id/upgrade' => 'buildings#upgrade', as: 'upgrade_building'
  post 'buildings/:id/upgrade' => 'buildings#upgrade_now'

  resources :missions do
    resources :missions, only: [:new, :create]
  end
  get 'missions/:id/redeem' => 'missions#redeem'

  resources :garrisons, only: [:show, :destroy, :new, :create]
  get ':type/:id/garrisons' => 'garrisons#index', as: 'garrisons_for'

  resources :stocks, except: [:index]

  resources :kingdoms
  
  get 'tiles/list' => 'tiles#list'
  post 'tiles/partial' => 'tiles#partial'
  resources :tiles
  resources :castles do
    resources :missions, only: [:new, :create]
    resources :garrisons, only: [:new, :create]
    resources :buildings, only: [:new, :create]
  end

  devise_for :users

  root 'tiles#index'

  

end

app/models/building.rb
class Building < ActiveRecord::Base
  belongs_to :building_type
  belongs_to :castle
  has_many :upgrades, through: :building_type
  validate :dont_overlapse, :in_bounds, :on_flat_land, :must_respect_max
  validate :must_upgrade, on: :update, :if => :building_type_id_changed?
  validate :must_be_basic, on: :create
  has_one :owner, through: :castle
  
  include Buyable
  self.buyer = :castle
  self.buyable_type = :building_type
  
  include ModApplier
  apply_mods_to :castle, provider: :building_type, direct: false
  
  def dont_overlapse
    errors.add(:base, "Cant place building on top of each other.") if overlapse?
  end
  
  def overlapse?
    Building.where.not(id: id).overlapsing(self).count > 0
  end
  
  def in_bounds
    if x + building_type.size_x - 1 >= bounds.x || x < 0
      errors.add(:x, "is out of bounds.")
    end
    if y + building_type.size_y - 1 >= bounds.x || x < 0
      errors.add(:y, "is out of bounds.")
    end
  end
  
  def on_flat_land
    errors.add(:base, "Must be place on flat land") unless castle.elevations.flat_zone?(elev_zone)
  end
  
  def must_respect_max
    errors.add(:base, "This castle allready have the maximum buildings of that type") unless respect_max?
  end
  
  def respect_max?
    return true if building_type.max_instances.nil? || building_type.max_instances.zero?
    castle.buildings.with_base_type(building_type).where.not(id: id).count < building_type.max_instances
  end
  
  def must_be_basic
    if bougth
      errors.add(:building_type_id, "This is an upgrade, it cant be build directly") unless building_type.predecessor_id.nil?
    end
  end
  
  def must_upgrade
    if bougth
      errors.add(:building_type_id, " can't be upgraded to") unless building_type.predecessor_id == building_type_id_was
    end
  end
  
  def bounds
    Point.new(16,16)
  end
  
  def can_upgrade?
    upgrades.count > 0
  end
  
  def owned_by?(user)
    !user.nil? && !owner.nil? && owner.id == user.id
  end
  
  scope :overlapsing, (lambda do |building|
    joins(:building_type).
      where(castle_id: building.castle_id).
      where("x + building_types.size_x > :x1 AND x < :x2 AND y + building_types.size_y > :y1 AND y < :y2", {
        x1: building.x,
        x2: building.x + building.building_type.size_x,
        y1: building.y,
        y2: building.y + building.building_type.size_y,
      })
  end)
  
  scope :with_base_type, (lambda do |building_type|
    base_id = building_type.base_id || building_type.id
    joins(:building_type).where("building_types.base_id = :base_id OR building_types.id = :base_id",{base_id:base_id})
  end)
  
  scope :upgradable, (lambda do ||
    joins(:upgrades)
  end)
  
  class << self
    
  end
  private
  
  def elev_zone
    Zone.new(x / 2,y / 2,(x + building_type.size_x - 1) / 2,(y + building_type.size_y - 1) / 2)
  end
end

app/models/building_type.rb
class BuildingType < ActiveRecord::Base
  has_many :costs, ->{ extending Quantifiable::HasManyExtension }, class_name: :Stock, as: :stockable
  has_many :modificators, as: :applier
  
  has_many :upgrades, class_name: "BuildingType",
                          foreign_key: "predecessor_id"
 
  belongs_to :predecessor, class_name: "BuildingType"
  belongs_to :base, class_name: "BuildingType"

  accepts_nested_attributes_for :costs, :modificators, allow_destroy: true
  
  before_save :update_base 
  
  include Randomizable
  extend InheritenceBaseNaming
  
  def alias
    name.parameterize('_')
  end
  
  scope :basic, (lambda do 
    where(:predecessor_id => nil)
  end)
  
  def update_base
    unless predecessor_id.nil?
      self.base_id = predecessor.base_id || predecessor.id 
      self.max_instances = nil
    end
  end
  
  def max_instances
    return base.max_instances unless base.nil?
    super
  end
  
  class << self
  
  end
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_action :set_building, only: [:show, :edit, :update, :destroy, :upgrade, :upgrade_now]
  before_action :set_my_castles, only: [:new, :create, :edit, :update]
  before_filter :authenticate_user!

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
    @building_types = BuildingType.basic.all
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)
    @building.bougth = true

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render action: 'show', status: :created, location: @building }
      else
        format.html { render action: 'new' }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /buildings/1/edit
  def edit
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /buildings/1/upgrade
  def upgrade
  end

  # POST /buildings/1/upgrade
  def upgrade_now
    @building.bougth = true
    respond_to do |format|
      if @building.update(params.require(:building).permit(:building_type_id))
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'upgrade' }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:x, :y, :building_type_id, :castle_id, :ready)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_building.html.erb
<% 
  elev = @castle.elevations true
  elevation = @castle.elevations.elevation(building.x/2,building.y/2)
  top = ElevationDisplay.top(building.x,building.y,elevation,size,2)
  left = ElevationDisplay.left(building.x,building.y,elevation,size,2)
%>
<%= tag("div", {class: ['building',building.building_type.alias], style: "top: #{top}px; left: #{left}px"}, true) %>
  <div class="display"></div>
  <div class="clickZone"></div>
  <ul class="actions">
    <li><%= link_to 'Show', building %></li>
    <% if building.owned_by?(current_user) && building.can_upgrade? %>
      <li><%= link_to 'Upgrade', upgrade_building_path(building) %></li>
    <% end %>
  </ul>
</div>

app/views/buildings/_form.html.erb
<%= form_for(@building) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :x %><br>
    <%= f.number_field :x %>
  </div>
  <div class="field">
    <%= f.label :y %><br>
    <%= f.number_field :y %>
  </div>
  
  <div class="building_types_slider">
    <a href="#" class="prev">Previous</a>
    <div class="building_types">
    <% @building_types.each do |building_type| %>
      <div class="building_type <%= building_type.alias %>" data-id="<%= building_type.id %>">
        <div class="imgFrame">
        </div>
        <h3><%= building_type.name %></h3>
        <div class="cost">
          <%= render building_type.costs  %>
        </div>
      </div>
    <% end %>
    </div>
    <a href="#" class="next">Next</a>
  </div>
  
  <div class="field">
    <%= f.label :building_type_id %><br>
    <%= f.collection_select(:building_type_id, @building_types, :id, :name, {}) %>
  </div>
  <% if params.has_key? 'castle_id' %>
    <%= f.hidden_field :castle_id, :value => params['castle_id'] %>
  <% else %>
    <div class="field">
      <%= f.label :castle_id %><br>
      <%= f.collection_select(:castle_id, @myCastles, :id, :name) %>
    </div>
  <% end %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing building</h1>

<%= render 'form' %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<h1>Listing buildings</h1>

<table>
  <thead>
    <tr>
      <th>X</th>
      <th>Y</th>
      <th>Building type</th>
      <th>Castle</th>
      <th>Ready</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.x %></td>
        <td><%= building.y %></td>
        <td><%= building.building_type %></td>
        <td><%= building.castle %></td>
        <td><%= building.ready %></td>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New building</h1>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>X:</strong>
  <%= @building.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @building.y %>
</p>

<p>
  <strong>Building type:</strong>
  <%= @building.building_type %>
</p>

<p>
  <strong>Castle:</strong>
  <%= @building.castle %>
</p>

<p>
  <strong>Ready:</strong>
  <%= @building.ready %>
</p>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/upgrade.html.erb
<h1>Editing building</h1>

<%= form_for(@building) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :building_type_id %><br>
    <%= f.collection_select(:building_type_id, @building.upgrades, :id, :name) %>
  </div>

  <div class="actions">
    <%= f.submit("upgrade") %>
  </div>
<% end %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>