config/routes.rb
GoodAndEvilKings::Application.routes.draw do

  get 'preview' => 'preview#index', as: 'preview'

  resources :message_categories

  resources :messages

  resources :diplomacies, only: [:index, :show]

  
  namespace :admin do
    resources :ai_actions
    resources :castles
    resources :building_types
    resources :mission_types
    resources :mission_lengths
    resources :mission_statuses
    resources :name_fragments
    resources :ressources
    resources :soldier_types
  end
  resources :buildings, except: [:index]
  get 'buildings/:id/upgrade' => 'buildings#upgrade', as: 'upgrade_building'
  post 'buildings/:id/upgrade' => 'buildings#upgrade_now'

  resources :missions do
    resources :missions, only: [:new, :create]
  end
  get 'missions/:id/redeem' => 'missions#redeem'

  resources :garrisons, only: [:show, :destroy, :new, :create]
  get ':type/:id/garrisons' => 'garrisons#index', as: 'garrisons_for'

  resources :stocks, except: [:index]

  resources :kingdoms
  
  get 'tiles/list' => 'tiles#list'
  post 'tiles/partial' => 'tiles#partial'
  resources :tiles
  resources :castles do
    resources :missions, only: [:new, :create]
    resources :garrisons, only: [:new, :create]
    resources :buildings, only: [:new, :create]
  end

  devise_for :users

  root 'tiles#index'

  

end

app/models/castle.rb
class Castle < ActiveRecord::Base
  belongs_to :kingdom
  has_one :owner, through: :kingdom, source: :user
  has_one :ai
  has_one :spawn_point, dependent: :nullify
  has_one :tile, as: :tiled, dependent: :destroy, validate: :true
  has_many :incomes, ->{ extending Quantifiable::HasManyExtension }, as: :stockable, inverse_of: :stockable
  has_many :stocks, -> { where(type: nil) }, as: :stockable, inverse_of: :stockable do
    include Quantifiable::HasManyExtension
    
    def add_qty(number, ressource)
      ressource = find_quantified_from(ressource)
      if(ressource.global)
        proxy_association.owner.kingdom.stocks.add_qty(number, ressource)
      else
        super(number, ressource)
      end
    end
    
    def add(quantifiables)
      quantifiables = Stock.new_enumerable(quantifiables)
      proxy_association.owner.kingdom.stocks.add(quantifiables.globals)
      super(quantifiables.locals)
    end
    
    def transfer(quantifiables)
      quantifiables = new_enumerable(quantifiables)
      proxy_association.owner.kingdom.stocks.transfer(quantifiables.globals)
      super(quantifiables.locals)
    end
    
    def up_to_date
      proxy_association.owner.incomes.apply(proxy_association.owner)
      self
    end
    
    def viewable_by?(user)
      proxy_association.owner.owned_by?(user)
    end
    
  end
  has_many :stocks_raw, ->{ extending Quantifiable::HasManyExtension }, class_name: :Stock, as: :stockable
  has_many(:garrisons, ->{ extending Garrison::HasManyExtension }, as: :garrisonable) do
    def viewable_by?(user)
      proxy_association.owner.owned_by?(user)
    end
  end
  has_many :buildings do
    def upgradable
      super.merge(proxy_association.owner.buyable_buildings())
    end
  end
  has_many :stationned_defence_missions, ->{ where(mission_status_code: "guarding") }, class_name: :DefenceMission, as: :target
  has_many :missions
  
  before_create :spawn_point_to_tile
  
  serialize :elevations_map, Array
  validates_presence_of :name
  
  include Modifiable
  prop_mod :max_stock, default: 1000
  prop_mod :recruitable_qty, default: 0
  prop_mod :pop, default: 5
  prop_mod "income:1"
  prop_mod "income:2"
  prop_mod "income:3"
  
  include Randomizable
  
  def tile=(val)
    return super(Tile.new(x:val.x,y:val.y)) if !val.is_a?(Tile) && val.respond_to?(:x) && val.respond_to?(:y)
    super(val)
  end
  
  def accessible_stocks
    incomes.apply(self)
    Stock.where(
      '("stocks"."stockable_type" = :type AND "stocks"."stockable_id" = :id) OR ("stocks"."stockable_type" = :kindom_type AND "stocks"."stockable_id" = :kindom_id)',
      {id: self.id,
      type: self.class.to_s,
      kindom_id: self.kingdom_id,
      kindom_type: "Kingdom"}
    ).where(type: nil)
  end
  
  def attacked(mission,battle)
    stationned_defence_missions.each do |mission|
      mission.attacked(mission,battle) if mission.respond_to?(:attacked)
    end
  end
  
  def max_stock(ressource = nil)
    super()
  end
  
  
  def default_income(id)
    10
  end
  
  def income(id,val)
    income = incomes.where(ressource_id: id.to_i).first
    if income.nil?  
      if new_record?
        incomes.new(ressource_id: id.to_i,qte: val.to_i)
      else
        incomes.create(ressource_id: id.to_i,qte: val.to_i)
      end
    else
      income.qte = val.to_i
      income.save!
    end
  end
  
  def remaining_recruitable_qty
    recruitable_qty - garrisons.not_ready.count
  end
  
  def on_stock_change(stock)
    if stock.type.nil?
      incomes.match(stock).each do |income|
        income.on_matching_updated(stock)
      end
    end
  end
  
  def on_stock_empty(income)
    garrisons.subtract(garrisons.get_upkeep_equiv(income))
  end

  def x
    tile.x
  end

  def y
    tile.y
  end
  
  def owned_by?(user)
    !user.nil? && kingdom.user_id == user.id
  end
  
  def elevations(save=false)
    if @elevations.nil?
      @elevations = Elevations.new(elevations_map)
      @elevations.on_gen do |e|
        self.elevations_map = e.map
      end
      if elevations_map.nil? || elevations_map.count == 0
        @elevations.gen
        self.save! if save
      end
    end
    @elevations
  end

  def distance(point)
    Math.hypot(point.x - x, point.y - y)
  end
  
  def buyable_buildings()
    if @buyable_buildings.nil?
      @buyable_buildings = Building.buyable_types_for(self.accessible_stocks)
    end
    @buyable_buildings
  end
  
  def buyable_troops()
    if @buyable_troops.nil?
      @buyable_troops = Garrison.buyable_types_for(self.accessible_stocks)
    end
    @buyable_troops
  end
  
  accepts_nested_attributes_for :tile
  accepts_nested_attributes_for :stocks, :garrisons, allow_destroy: true

  default_scope { includes(:kingdom) }
  
  
  def generate_name!
    self.name = Castle.generate_name
  end
  
  def spawn_point_to_tile
    self.tile = Tile.new_from_point(spawn_point) if tile.nil? && !spawn_point.nil?
  end
  
  class << self
  
    def new_auto_named(vals)
      vals[:name] = generate_name
      new(vals)
    end
    
    def generate_name
      NameFragment.generate_until(:castle) { |name|
        Castle.where(name: name).count == 0
      }.humanize
    end
    
  end
end

app/controllers/admin/castles_controller.rb
module Admin
  class CastlesController < AdminController
    before_action :set_castle, only: [:show, :edit, :update, :destroy]

    # GET /castles
    # GET /castles.json
    def index
      @castles = Castle.all.includes(:tile)
    end
    
    # GET /castles/1
    # GET /castles/1.json
    def show
    end

    # GET /castles/new
    def new
      @castle = Castle.new
    end

    # GET /castles/1/edit
    def edit
    end

    # POST /castles
    # POST /castles.json
    def create
      @castle = Castle.new(castle_params)

      respond_to do |format|
        if @castle.save
          format.html { redirect_to [:admin, @castle], notice: 'Castle was successfully created.' }
          format.json { render action: 'show', status: :created, location: @castle }
        else
          format.html { render action: 'new' }
          format.json { render json: @castle.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /castles/1
    # PATCH/PUT /castles/1.json
    def update
      respond_to do |format|
        if @castle.update(castle_params)
          format.html { redirect_to [:admin, @castle], notice: 'Castle was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: 'edit' }
          format.json { render json: @castle.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /castles/1
    # DELETE /castles/1.json
    def destroy
      @castle.destroy
      respond_to do |format|
        format.html { redirect_to admin_castles_url }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_castle
        @castle = Castle.find(params[:id])
      end
      
      # Never trust parameters from the scary internet, only allow the white list through.
      def castle_params
        params.require(:castle).permit(:name, :kingdom_id, stocks_attributes: [:qte, :ressource_id, :id, :_destroy], garrisons_attributes: [:qte, :soldier_type_id, :id, :_destroy], tile_attributes: [:x, :y, :id, :_destroy])
      end
    
  end
end

app/controllers/castles_controller.rb
class CastlesController < ApplicationController
  before_action :set_castle, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except: [:show]
  before_filter :must_be_mine!, only: [:edit, :update, :destroy]

  # GET /castles
  # GET /castles.json
  def index
    @castles = current_user.current_kingdom.castles.includes(:tile)
  end
  
  # GET /castles/1
  # GET /castles/1.json
  def show
  end

  # GET /castles/new
  def new
    @castle = Castle.new
  end

  # GET /castles/1/edit
  def edit
  end

  # POST /castles
  # POST /castles.json
  def create
    @castle = Castle.new(castle_params)

    respond_to do |format|
      if @castle.save
        format.html { redirect_to @castle, notice: 'Castle was successfully created.' }
        format.json { render action: 'show', status: :created, location: @castle }
      else
        format.html { render action: 'new' }
        format.json { render json: @castle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /castles/1
  # PATCH/PUT /castles/1.json
  def update
    respond_to do |format|
      if @castle.update(castle_params)
        format.html { redirect_to @castle, notice: 'Castle was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @castle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /castles/1
  # DELETE /castles/1.json
  def destroy
    @castle.destroy
    respond_to do |format|
      format.html { redirect_to castles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_castle
      @castle = Castle.find(params[:id])
    end
    
    def must_be_mine!
      raise AccessDenied unless @castle.owned_by?(current_user)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def castle_params
      params.require(:castle).permit(:name)
    end
	
	
end

app/helpers/castles_helper.rb
module CastlesHelper
end

app/views/castles/_castle.html.erb
<% 
  classes = ['castle']
  if user_signed_in? && castle.owned_by?(current_user)
    classes.push('mine')
  end
%>
<div class="<%= classes.join(" ") %>" style="top:<%= pos.y %>px;left:<%= pos.x %>px;">
	<div class="clickPixel"></div>
  <span class="name"><%= castle.name %></span>
  <ul class="actions">
    <%= link_to 'Show', castle %>
    <% if user_signed_in? %>
      <%= link_to 'Mission', new_castle_mission_path(castle.id) %>
    <% end %>
  </ul>
</div>

app/views/castles/_elevations.html.erb
<div class="elevations">
<% 
  elev = @castle.elevations true
  elev.each_display_order do |x,y,elevation|
    top = ElevationDisplay.top(x,y,elevation,size)
    left = ElevationDisplay.left(x,y,elevation,size)
%>
  <%= tag("div", {class: 'elevation', posx: x, posy: y, elevation: elevation, style: "top: #{top}px; left: #{left}px"}, true) %>
    <div class="ground"></div>
    <div class="leftWall tall<%= elevation - (elev.elevation(x,y+1) || 0) %>"></div>
    <div class="rightWall tall<%= elevation - (elev.elevation(x+1,y) || 0) %>"></div>
  </div>
<%
  end 
%>
</div>

app/views/castles/_form.html.erb
<%= nested_form_for @castle do |f| %>
  <% if @castle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@castle.errors.count, "error") %> prohibited this castle from being saved:</h2>

      <ul>
      <% @castle.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/castles/edit.html.erb
<h1>Editing castle</h1>

<%= render 'form' %>

<%= link_to 'Show', @castle %> |
<%= link_to 'Back', castles_path %>

app/views/castles/index.html.erb
<h1>My castles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Pop</th>
      <th></th>
      <th></th>
      <th></th>
      <% if user_signed_in? %>
        <th></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @castles.each do |castle| %>
      <tr>
        <td><%= castle.name %></td>
        <td><%= castle.x %>; <%= castle.y %></td>
        <td><%= castle.pop %></td>
        <td><%= link_to 'Show', castle %></td>
        <td><%= link_to 'Edit', edit_castle_path(castle) %></td>
        <td><%= link_to 'Destroy', castle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% if user_signed_in? %>
          <td><%= link_to 'Mission', new_castle_mission_path(castle.id) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Castle', new_castle_path %>

app/views/castles/new.html.erb
<h1>New castle</h1>

<%= render 'form' %>

<%= link_to 'Back', castles_path %>

app/views/castles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @castle.name %>
</p>

<p>
  <strong>Kingdom:</strong>
  <%= @castle.kingdom.name %>
</p>

<% if @castle.stocks.viewable_by?(current_user) %>
  <%= render 'stocks/bars', stockable: @castle %>
<% end %>

<% if @castle.garrisons.viewable_by?(current_user) %>
<div class="garrisons">
  <%= render @castle.garrisons.renderable %>
</div>
<% end %>

<div class="missions">
  <%= render Mission.ongoing.concerning(@castle).viewable_by(current_user) %>
</div>

<ul class="actions">
  <% if user_signed_in? %>
    <%= nav_link 'Mission', new_castle_mission_path(@castle.id) %>
  <% end %>
  <% if @castle.owned_by?(current_user) %>
    <%= nav_link 'Recrute', new_castle_garrison_path(@castle.id) %>
    <%= nav_link 'Build', new_castle_building_path(@castle.id) %>
    <%= nav_link 'Edit', edit_castle_path(@castle) %>
    <%= nav_link 'Garrisons', garrisons_for_path('castles',@castle.id) %>
  <% end %>
  <%= nav_link 'Back', castles_path %>
</ul>

<div class="graphics">
  <%= render 'elevations', :size => 200 %>
  <div class="buildings">
    <% @castle.buildings.each do |building| %>
      <%= render building, :size => 200 %>
    <% end %>
  </div>
</div>